name: Testing

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cassandra-version: ['4.0', '4.1']
        include:
          - cassandra-version: '4.1'
            set-version: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - if: ${{ !matrix.set-version }}
        name: Build with Maven (Cassandra 4.0 and lower)
        run: mvn -B clean package -DskipTests --file pom.xml
      - if: ${{ !matrix.set-version }}
        name: run tests (Cassandra 4.0 and lower)
        run: mvn -B test --file pom.xml
      - if: ${{ matrix.set-version }}
        name: Build with Maven (Cassandra 4.1 and newer)
        run: mvn -B clean package -DskipTests --file pom.xml -Dcassandra.version=4.1-beta1
      - if: ${{ matrix.set-version }}
        name: run tests (Cassandra 4.1 and newer)
        run: mvn -B test --file pom.xml -Dcassandra.version=4.1-beta1
